apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cdac-project-cluster
  region: us-east-1

nodeGroups:
  - name: cdac-project-ng
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 40
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: cdac-project-ng2
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 40
    ssh:
      publicKeyPath: nveg.pub