apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: cdac-project
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: registry.hub.docker.com/8077103273/cdac-project:%IMAGE_NO%
        ports:
        - containerPort: 5000